fix: duplex print not working
xaralis/ksicht pull request #43
Opened 2024-10-29 02:12 UTC by FelyCZ

I've improved the way we handle duplex printing by adding blank pages at the time of printing without any slowdown using a temporary file stored in MEDIA root.

I'm not sure why we save each submission file twice (one normal and one duplex), as it only leads to double the space required.
Should probably be fixed in the next code review...

@xaralis Can you please take a look at the edits I made and, if you don't find any problems, publish, so Kuba is able to generate the prints? Thx!

2024-10-30 17:17 UTC, xaralis requested changes
Mám za to, že ta duplex varianta se tam rovnou ukládala právě kvůli rychlosti. Zkoušel jsi to nad klonem reálný DB kde těch řešení je fakt hodně? Pokud to funguje uspokojivě rychle tak za mě klidně, ale byl bych opatrný.

2024-10-30 17:17 UTC, xaralis commented on ksicht/pdf.py
> +        writer.add_blank_page(width=8.27 * 72, height=11.7 * 72)
Prosím použijme `PaperSize` ať je to aspoň trochu readable:

https://pypdf.readthedocs.io/en/latest/modules/PaperSize.html#add-blank-page-with-papersize

2024-10-30 17:17 UTC, xaralis commented on ksicht/settings.py
> +BLANK_PDF_FILEPATH = MEDIA_ROOT + "/" + "blank_page.pdf"
```suggestion
BLANK_PDF_FILEPATH = os.path.join(MEDIA_ROOT, "blank_page.pdf")
```

2024-11-03 19:46 UTC, FelyCZ commented
> Mám za to, že ta duplex varianta se tam rovnou ukládala právě kvůli rychlosti. Zkoušel jsi to nad klonem reálný DB kde těch řešení je fakt hodně? Pokud to funguje uspokojivě rychle tak za mě klidně, ale byl bych opatrný.

Zkoušel, ba dokonce tím vyexportoval duplex pdf pro aktuální sérii a nezaznamenal jsem rozdíl v rychlosti oproti současnému řešení. 
Myslím si, že to bylo důležité v minulosti, kdy jsme export ještě nedělali pomocí pdfrw ale PyPDF a z té doby to tam asi i zůstalo.

Nemazal jsem kód pro ukládání duplex pdf souborů, ale již by to nemělo být potřeba.

2024-11-04 12:09 UTC, xaralis approved these changes

2024-11-04 12:10 UTC, xaralis commented
@FelyCZ Mám to teda nasadit?

2024-11-04 12:11 UTC, FelyCZ commented
@xaralis Ano, prosím.

2024-11-04 12:31 UTC, merged

2024-11-04 12:38 UTC, xaralis commented
Nasazeno.